config/routes.rb
Rails.application.routes.draw do
  resources :stores
  controller :admin do
    get 'admin' => :index
    get 'open' => :open
    post 'save' => :save
    get 'edit' => :edit
  end

  controller :sessions do
    get 'login' => :new # 'sessions/new'
    post 'login' => :create # 'sessions/create'
    delete 'logout' => :destroy # 'sessions/destroy'
  end

  resources :users

  root 'admin#index'

end

app/models/store.rb
class Store < ActiveRecord::Base #The store scaffold model
  belongs_to :user
  validates :name, presence: true, uniqueness: true
  validates :predator, :prey, :time, numericality: { only_integer: true }, allow_blank: true
  validates :alpha, :beta, :gamma, :delta, :timeincrement, numericality: true, allow_blank: true

  def flag

  end
end

app/controllers/stores_controller.rb
class StoresController < ApplicationController
  before_action :set_store, only: [:show, :edit, :update, :destroy]
                    #This is the scaffold that saves the data into the database
  # GET /stores
  # GET /stores.json
  def index
    @stores = Store.all
  end

  # GET /stores/1
  # GET /stores/1.json
  def show
  end

  # GET /stores/new
  def new
    @user_id = session[:user_id]
    @store = Store.new

    @store.alpha = 0.15
    @store.beta = 0.001
    @store.gamma = 0.25
    @store.delta = 0.00015
    @store.time = 50
    @store.timeincrement = 0.5

    respond_to do |format|
      format.html # new.html.erb
      format.html {render json: @store }
    end
  end

  # GET /stores/1/edit
  def edit
  end

  # POST /stores
  # POST /stores.json
  def create
    @user_id = session[:user_id]
    @store = Store.new(store_params)
    @store[:user_id] = @user_id
    respond_to do |format|
      if @store.save
        format.html { redirect_to url_for(:controller => "admin", :action => "edit", :save_id => @store.id ), notice: 'Saved!' }
        format.json { render :show, status: :created, location: @store }
      else
        format.html { redirect_to admin_url }
        format.json { render json: @store.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /stores/1
  # PATCH/PUT /stores/1.json
  def update
    respond_to do |format|
      if @store.update(store_params)
        format.html { redirect_to admin_url, notice: 'Saved!' }
        format.json { render :show, status: :ok, location: @store }
      else
        format.html { render :edit }
        format.json { render json: @store.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /stores/1
  # DELETE /stores/1.json
  def destroy
    @store.destroy
    respond_to do |format|
      format.html { redirect_to url_for(:controller => :admin, :action => :open), notice: 'Deleted!' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_store
      @store = Store.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def store_params
      params.require(:store).permit(:name, :predator, :prey, :alpha, :beta, :gamma, :delta, :time, :timeincrement, :user_id)
    end

    def flag_param
      params.require(:store).permit(:flag)
    end
end

app/helpers/stores_helper.rb
module StoresHelper
end

app/views/stores/_form.html.erb
<%= form_for(@store) do |f| %>
  <% if @store.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@store.errors.count, "error") %> prohibited this store from being saved:</h2>

      <ul>
      <% @store.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :predator %><br>
    <%= f.number_field :predator, size: 20 %>
  </div>
  <div class="field">
    <%= f.label :prey %><br>
    <%= f.number_field :prey, size: 20 %>
  </div>
  <div class="field">
    <%= f.label :alpha %><br>
    <%= f.text_field :alpha, size: 20 %>
  </div>
  <div class="field">
    <%= f.label :beta %><br>
    <%= f.text_field :beta, size: 20 %>
  </div>
  <div class="field">
    <%= f.label :gamma %><br>
    <%= f.text_field :gamma, size: 20 %>
  </div>
  <div class="field">
    <%= f.label :delta %><br>
    <%= f.text_field :delta, size: 20 %>
  </div>
  <div class="field">
    <%= f.label :time %><br>
    <%= f.number_field :time, size: 20 %>
  </div>
  <div class="field">
    <%= f.label :timeincrement %>
    <%= f.text_field :timeincrement, size: 20 %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>

  <input type="button" id="submit" onclick="drawGraph()" value="Draw Graph">

  <div class="graph">
    <div id="placeholder" class="demo-placeholder" style="height:800px; width:1000px"></div>	
  </div>
<% end %>

app/views/stores/edit.html.erb
<h1>Editing Store</h1>

<%= render 'form' %>

app/views/stores/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Stores</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Predator</th>
      <th>Prey</th>
      <th>Alpha</th>
      <th>Beta</th>
      <th>Gamma</th>
      <th>Delta</th>
      <th>Time</th>
      <th>Increment</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @stores.each do |store| %>
      <tr>
        <td><%= store.name %></td>
        <td><%= store.predator %></td>
        <td><%= store.prey %></td>
        <td><%= store.alpha %></td>
        <td><%= store.beta %></td>
        <td><%= store.gamma %></td>
        <td><%= store.delta %></td>
        <td><%= store.time %></td>
        <td><%= store.timeincrement %></td>
        <td><%= store.user_id %></td>
        <td><%= link_to 'Show', store %></td>
        <td><%= link_to 'Edit', edit_store_path(store) %></td>
        <td><%= link_to 'Destroy', store, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Store', new_store_path %>

app/views/stores/new.html.erb
<!--<h1>New Store</h1>-->

<nav>
<ul>
  <li>
  <div class="dropdown">
    <a href="#" class="dropbtn">File</a>
    <div class="dropdown-content">
      <a id="submit-btn" class="submit-btn">Save</a>
      <a href="#">SaveAs</a>
      <a href="#">Open</a>
    </div>
  </div>
  </li>
  <li><a>Edit</a></li>
  <li><a>Help boga oooooooga</a></li>
</ul>
</nav>

<%= render 'form' %>

app/views/stores/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @store.name %>
</p>

<p>
  <strong>Predator:</strong>
  <%= @store.predator %>
</p>

<p>
  <strong>Prey:</strong>
  <%= @store.prey %>
</p>

<p>
  <strong>Alpha:</strong>
  <%= @store.alpha %>
</p>

<p>
  <strong>Beta:</strong>
  <%= @store.beta %>
</p>

<p>
  <strong>Gamma:</strong>
  <%= @store.gamma %>
</p>

<p>
  <strong>Delta:</strong>
  <%= @store.delta %>
</p>

<p>
  <strong>Time:</strong>
  <%= @store.time %>
</p>

<p>
  <strong>Increment:</strong>
  <%= @store.timeincrement %>
</p>

<p>
  <strong>User:</strong>
  <%= @store.user_id %>
</p>

<%= link_to 'Edit', edit_store_path(@store) %> |
<%= link_to 'Back', stores_path %>